### Importamos las librerias necesarias

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from apyori import apriori

### Importamos el dataset

In [10]:
dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None)
dataset.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Vemos la forma de nuestro dataset para ver como lo recorremos para ordenar las transacciones

In [12]:
dataset.shape

(7501, 20)

### Recorremos el dataset ordenando cada una de las transacciones

In [13]:
transactions = []
for i in range(0, 7501):
    transactions.append([str(dataset.values[i,j]) for j in range(0, 20)])
#transactions

### Entrenamos el algoritmo apriori pasandole las transacciones y los parametros que definamos

In [18]:
rules = apriori(transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2)
results = list(rules)
#results

### Definimos una funcion que nos ayude a visualizar los resultado de manera mas ordenada

In [19]:
def inspect(results):
    lh          = [tuple(result[2][0][1]) for result in results] 
    rh 			= [tuple(result[2][0][0]) for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(rh, lh, supports, confidences, lifts))

### Usamos la funcion anteriormente definida para crear un dataframe para visualizar los resultados

In [23]:
inspect_results=pd.DataFrame(inspect(results),columns=['Ancedente','Consecuente','Soporte','Confianza','Lift'])
inspect_results

,Ancedente,Consecuente,Soporte,Confianza,Lift
0,"(light cream,)","(chicken,)",0.004533,0.290598,4.843951
1,"(mushroom cream sauce,)","(escalope,)",0.005733,0.300699,3.790833
2,"(pasta,)","(escalope,)",0.005866,0.372881,4.700812
3,"(fromage blanc,)","(honey,)",0.003333,0.245098,5.164271
4,"(herb & pepper,)","(ground beef,)",0.015998,0.323450,3.291994
...,...,...,...,...,...
155,"(olive oil, ground beef)","(nan, spaghetti, mineral water)",0.003066,0.216981,3.632981
156,"(pancakes, ground beef)","(nan, spaghetti, mineral water)",0.003066,0.211009,3.532991
157,"(tomatoes, ground beef)","(nan, spaghetti, mineral water)",0.003066,0.261364,4.376091
158,"(milk, spaghetti, mineral water)","(nan, olive oil)",0.003333,0.211864,3.223519
159,"(tomatoes, milk)","(nan, spaghetti, mineral water)",0.003333,0.238095,3.986501