### Importamos las librerias

In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.frequent_patterns import apriori, association_rules

### Importamos el dataset de movie

In [2]:
dataset_movies = pd.read_csv('movies.csv')
dataset_ratings = pd.read_csv('ratings.csv')

### Analizamos el data set para construir el dataset final para sacar las recomendaciones

In [3]:
dataset_movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
dataset_ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

### Unimos los dataset por la columna en comun movieId

In [5]:
dataset_unido = pd.merge(dataset_ratings,dataset_movies, on="movieId")
dataset_unido

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,847434962,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,1106635946,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,1510577970,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,1305696483,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...,...
100831,610,160341,2.5,1479545749,Bloodmoon (1997),Action|Thriller
100832,610,160527,4.5,1479544998,Sympathy for the Underdog (1971),Action|Crime|Drama
100833,610,160836,3.0,1493844794,Hazard (2005),Action|Drama|Thriller
100834,610,163937,3.5,1493848789,Blair Witch (2016),Horror|Thriller
100835,610,163981,3.5,1493850155,31 (2016),Horror

### Sacamos todos los registros con un rating menor a 4 y quitamos las columnas timestamp y genres

In [6]:
filtro_rating = dataset_unido['rating'] >= 4
dataset_filtrado = dataset_unido[filtro_rating]
dataset_filtrado=dataset_filtrado.drop('timestamp',axis=1)
dataset_filtrado=dataset_filtrado.drop('genres',axis=1)
dataset_filtrado

        userId  movieId  rating                             title
0            1        1     4.0                  Toy Story (1995)
1            5        1     4.0                  Toy Story (1995)
2            7        1     4.5                  Toy Story (1995)
4           17        1     4.5                  Toy Story (1995)
6           19        1     4.0                  Toy Story (1995)
...        ...      ...     ...                               ...
100819     610   141400     4.0         Invincible Shaolin (1978)
100822     610   142598     4.0                 Last Shift (2014)
100824     610   146309     4.0      The Boy and the Beast (2015)
100825     610   147657     4.0            Masked Avengers (1981)
100832     610   160527     4.5  Sympathy for the Underdog (1971)

[48580 rows x 4 columns]

### Sacamos los valores unicos de los usuer id y de los titulos

In [7]:
userId=dataset_filtrado['userId'].unique()
userId.sort()
movies_title=dataset_filtrado['title'].unique()

### Creamos el dataset de salida con los datos en cero, los index con nuestros usuarios y las columnas las peliculas

In [8]:
dataset_final=pd.DataFrame(data='0', index=userId, columns=movies_title)
dataset_final

,Toy Story (1995),Grumpier Old Men (1995),Heat (1995),Seven (a.k.a. Se7en) (1995),"Usual Suspects, The (1995)",From Dusk Till Dawn (1996),Bottle Rocket (1996),Braveheart (1995),Rob Roy (1995),Canadian Bacon (1995),...,Reality (2014),Spring (2015),The Magnificent Ruffians (1979),Tokyo Tribe (2014),The Witch (2015),Invincible Shaolin (1978),Last Shift (2014),The Boy and the Beast (2015),Masked Avengers (1981),Sympathy for the Underdog (1971)
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
607,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
608,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
610,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Necesitamos crear dos listas, una con los titulos de las peliculas y la otra con los id de los usuarios

In [9]:
list_titulos=list(movies_title)
list_user=list(userId)

### Recorro el dataset original usuario por usuario y coloco en el dataset final si el usuario vio la pelicula

In [12]:
error = 0 #Mide las veces que no encontro la pelicula
for user in list_user: # Uso la lista de usuarios para hacer el for
    # Hago el filtro para seleccionar todas las peliculas de un solo usuario
    filtro_user = dataset_filtrado['userId'] == user 
    dataset_user = dataset_filtrado[filtro_user]
    # Cuento la cantidad de peliculas de ese usuario particular 
    num_pelis=len(dataset_user)
    # Recorro con otro for cada una de las peliculas de este usuario en particular 
    for row in range(num_pelis):
        # Saco el nombre de cada pelicula
        title_user = dataset_user.iloc[row,3]
        if list_titulos.count(title_user)>0:
            # Obtengo la posicion de la columna donde se encuentra la pelicula
            col=list_titulos.index(title_user)
            try:
                #Voy moviendo el puntero del user 
                ptr=list_user.index(user)
                #Cambio el valor en el dataset final correspondiente al usuario y a la pelicula
                dataset_final.iloc[ptr,col]=1
            except Exception as error:
                print(type(error),col,title_user,user)
        else:
            error = error+1
dataset_final

,Toy Story (1995),Grumpier Old Men (1995),Heat (1995),Seven (a.k.a. Se7en) (1995),"Usual Suspects, The (1995)",From Dusk Till Dawn (1996),Bottle Rocket (1996),Braveheart (1995),Rob Roy (1995),Canadian Bacon (1995),...,Reality (2014),Spring (2015),The Magnificent Ruffians (1979),Tokyo Tribe (2014),The Witch (2015),Invincible Shaolin (1978),Last Shift (2014),The Boy and the Beast (2015),Masked Avengers (1981),Sympathy for the Underdog (1971)
1,1,1,1,1,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,1,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0,0,0,0,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
607,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
608,0,0,0,1,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
610,1,0,1,1,1,1,0,1,0,0,...,1,1,1,1,1,1,1,1,1,1

### Para usar la funcion apriory de mlxtend necesitamos que los valores sean boleanos

In [51]:
for user in list_user: # Uso la lista de usuarios para hacer el for
    for movie in list_titulos:
        # Saco el nombre de cada pelicula
        col=list_titulos.index(movie)
        row=list_user.index(user)
        if  dataset_final.iloc[row,col]==1:
            dataset_final.iloc[row,col]= True
        else:
            dataset_final.iloc[row,col]= False
dataset_final

### El proceso demora mucho por lo que importamos el dataset listo por cuestiones de tiempo

In [46]:
dataset_true_false = pd.read_csv('dataset_true_false.csv', sep=';',index_col = 0)
dataset_true_false

,Toy Story (True995),Grumpier Old Men (True995),Heat (True995),Seven (a.k.a. Se7en) (True995),"Usual Suspects, The (True995)",From Dusk Till Dawn (True996),Bottle Rocket (True996),Braveheart (True995),Rob Roy (True995),Canadian Bacon (True995),...,Reality (2FalseTrue4),Spring (2FalseTrue5),The Magnificent Ruffians (True979),Tokyo Tribe (2FalseTrue4),The Witch (2FalseTrue5),Invincible Shaolin (True978),Last Shift (2FalseTrue4),The Boy and the Beast (2FalseTrue5),Masked Avengers (True98True),Sympathy for the Underdog (True97True)
1,True,True,True,True,True,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,True,False,False,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,False,False,False,False,True,True,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
607,True,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
608,False,False,False,True,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
609,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
610,True,False,True,True,True,True,False,True,False,False,...,True,True,True,True,True,True,True,True,True,True

### Entrenamos el modelo con la funcion apriori de la libreria mlxtend

In [49]:
f=apriori(dataset_true_false, min_support=0.2, use_colnames=True, max_len=2)

### Vemos las reglas generadas

In [50]:
rules=association_rules(f,metric='lift',min_threshold=2)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Star Wars: Episode IV - A New Hope (True977)),(Star Wars: Episode V - The Empire Strikes Back (True98False)),0.330049,0.275862,0.236453,0.716418,2.597015,0.145405,2.553539
1,(Star Wars: Episode V - The Empire Strikes Back (True98False)),(Star Wars: Episode IV - A New Hope (True977)),0.275862,0.330049,0.236453,0.857143,2.597015,0.145405,4.689655
2,(Star Wars: Episode VI - Return of the Jedi (True983)),(Star Wars: Episode IV - A New Hope (True977)),0.246305,0.330049,0.206897,0.840000,2.545075,0.125604,4.187192
3,(Star Wars: Episode IV - A New Hope (True977)),(Star Wars: Episode VI - Return of the Jedi (True983)),0.330049,0.246305,0.206897,0.626866,2.545075,0.125604,2.019901